{
 "title": "Anomaly",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Humans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "persons",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Piaza Anomaly Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "anomaly",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Word Cloud",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "label" ], "type": "tag" }
     ],
     "measurement": "objects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "Persons",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" }
     ],
     "measurement": "objects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=", "value": "person" }
     ]
    },
    {
     "alias": "Cars",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" }
     ],
     "measurement": "objects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=", "value": "car" }
     ]
    },
    {
     "alias": "Bicycles",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" }
     ],
     "measurement": "objects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=", "value": "bicycle" }
     ]
    }
   ]
  },
  {
   "title": "Total Number of Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "camera" ], "type": "tag" }
     ],
     "measurement": "objects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}