{
 "title": "Specific Place",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "locations",
     "select": [
      [
       { "params": [ "geohash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Anomalies",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "camera" ], "type": "tag" }
     ],
     "measurement": "anomaly",
     "query": "SELECT * FROM \"anomaly\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "score" ], "type": "field" }
      ],
      [
       { "params": [ "video_timestamp" ], "type": "field" }
      ],
      [
       { "params": [ "url" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Objects Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "Persons",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" }
     ],
     "measurement": "objects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=", "value": "person" }
     ]
    },
    {
     "alias": "Cars",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" }
     ],
     "measurement": "objects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=", "value": "car" }
     ]
    },
    {
     "alias": "Bicycles",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "label" ], "type": "tag" }
     ],
     "measurement": "objects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "label", "operator": "=", "value": "bicycle" }
     ]
    }
   ]
  },
  {
   "title": "Number of Humans",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "persons",
     "select": [
      [
       { "params": [ "score" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  }
 ]
}