{
 "title": "Twitter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heat Tweets",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "locations",
     "select": [
      [
       { "params": [ "geohash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tweets By Day",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "emotions",
     "select": [
      [
       { "params": [ "nrcDict_Trust" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Hate Tweets By Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hate",
     "select": [
      [
       { "params": [ "classification" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Emotions By Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "alias": "Anger",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "emotions",
     "select": [
      [
       { "params": [ "nrcDict_Anger" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Joy",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "emotions",
     "select": [
      [
       { "params": [ "nrcDict_Joy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Fear",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "emotions",
     "select": [
      [
       { "params": [ "nrcDict_Fear" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}